@include('include.header',['page_title' => 'Home | Eventiary'])
@include('include.home.banner')
@include('include.home.categories')
@include('include.home.recent')
@include('include.home.top_organizers')
@include('include.home.testimonials')
@include('include.home.create_event')
@include('include.footer')